version: '3'
services:
  RStudio:
    image: rocker/ml:4.2.0-cuda11.1
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=root
      - DISPLAY=10.0.75.1:0.0
    volumes:
      - ./data/:/home/rstudio/data/
      - ./Setting:/home/rstudio/.config
      # - ./Setting_Rstudio:/home/rstudio/.rstudio/monitored/user-settings
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]